---
- name: Test playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Task to get server name
      ansible.builtin.debug:
        msg: "This playbook running in  {{ ansible_hostname }}"
